### ISSUE TITLE
Sprint 3

### ISSUE THREAD

**Issue by jonleung** [jonleung/temp#1]
#### Sprint Goals
1. Reconnect with club leaders and ensure proper succession
2. Build MVP of club in a box for introductory materials
3. Make progress with fundraising, identify foundations and individuals and
   get connected with them.
4. Onboard wilsonhsieh
#### Sprint Participants

xeonjake Cydrobolt wilsonhsieh jonleung zachlatta
#### Sprint Deliverables
- [ ] Club in a box
  - [x] Collect data from club leaders and make sure everyone, if needed, has
    a successor hackedu/hackedu#21 (jonleung)
  - [x] Make Twilio workshops accessible hackedu/hackedu#22 (jonleung)
  - [x] Write blog post on the "Google philosophy" (jonleung)
  - [x] Finish the _Joining Community_ slides (jonleung)
  - [ ] Clean up migrated materials hackedu/hackedu#14 (jonleung)
  - [x] Basic stuff for starting clubs
    - [x] Club constitution hackedu/hackedu#15 (jonleung)
    - [x] Club budget hackedu/hackedu#20 (jonleung)
    - [x] Attendance sheet hackedu/hackedu#23 (jonleung)
  - [x] Lesson structure document hackedu/hackedu#24 (jonleung)
- [ ] Fundraising
  - [ ] Lunch with Google zachlatta/fundraising#18 (zachlatta)
  - [ ] Identify and find contacts at potential education foundations
    zachlatta/fundraising#19 (zachlatta)
  - [ ] Identify potential donors that Richard has connections with
    zachlatta/fundraising#20 (zachlatta)
  - [x] Get intros from Quinn to potential donors (zachlatta)
  - [x] Get intros from Ryan to potential donors (zachlatta)
  - [ ] Audible free accounts zachlatta/fundraising#21 (zachlatta)
  - [x] Create list of potential donors from your network
    zachlatta/fundraising#22 (jonleung)
    - [ ] Write and send emails to reach out to jonleung's potential donors
      (zachlatta)
  - [ ] Get introduction to Microsoft (zachlatta)
  - [ ] Get introduction to the Intel Education Foundation from Austin Carvey
- [ ] Other
  - [ ] Read through documentation on GitHub & talk to zachlatta/jonleung to
    understand where we're at (wilsonhsieh)
  - [ ] Identify the biggest needs in the organization (wilsonhsieh)
  - [ ] Put together markdown lesson plan for FizzBuzz workshop
    hackedu/hackedu#25 (Cydrobolt)
  - [ ] Convert club documents to GitHub markdown (xeonjake)
    - [ ] Club constitution
    - [ ] Club budgets (may be related to hackedu/hackedu#20)
  - [x] Create IRCCloud accounts for amysorto, xeonjake, and wilsonhsieh
    (zachlatta)
  - [x] Add wilsonhsieh to GitHub team (zachlatta)
  - [ ] Send things to xeonjake and Cydrobolt (jonleung)
  - [ ] Send out sprint discussion survey to xeonjake, Cydrobolt,
    wilsonhsieh, amysorto, jonleung, and zachlatta (jonleung)

---
- [ ] Backlog
  - [ ] Google Adwords zachlatta/fundraising#23 (zachlatta)
